### ISSUE TITLE
#US02 Como Empleado del estacionamiento, Deseo llevar un control de los vehículos ingresados e egresados y los que están en el estacionamiento a su vez el monto a cobrar por el tiempo utilizado.

### ISSUE THREAD

**Issue by jonjonathanarias** [jonjonathanarias/ProyectoFullStack#2]
Es sumamente importante para una gestion apropiada por parate de la empresa contar con la informacion de cada uno de los vehiculos

**Comment by josecolombotk** [comment]
#TK02 Referenciando a US02
 Registro de vehículo, ya sea motocicleta, auto, camionetas, etcétera, por patente. 
Registro de fecha y hora de entrada .
Cálculo del tiempo que el vehículo pasó estacionado .
Ajuste de costo por hora con redondeo y tolerancia
